### PR TITLE
Update build tools

### PR DESCRIPTION
**Pull request by bmeike**

### CODE REVIEW

**Comment by bmeike** [comment]
Hey @zaki50 :  where are the build files that I need to edit to get this to work?

**Comment by zaki50** [comment]
only the file at the top directory

**Comment by zaki50** [comment]
After you'll execute `./gradlew wrapper`, you'll need to edit `gradle/wrapper/gradle-wrapper.properties` to use `all.zip` instead of `bin.zip` in `distributionUrl` property`.

**Comment by zaki50** [comment]
@bmeike I pushed the fix.

**Comment by bmeike** [comment]
Thanks for the help on this, @zaki50 !  On the other hand, give a man a fish and he eats for a day.  Teach a man to fish and he eats for a lifetime... ;-)

**Pull request merged**
