### PR TITLE
RealmRecyclerViewAdapter uses RealmModel instead of RealmObject.

### LINKED ISSUE #29: RealmRecyclerViewAdapter uses RealmObject instead of RealmModel
In the RealmRecyclerViewAdapter : 
`public abstract class RealmRecyclerViewAdapter<T extends RealmObject, VH extends RecyclerView.ViewHolder> `
But T should extends RealmModel instead (like the RealmBaseAdapter).

### PR DESCRIPTION
**Pull request by dalinaum**
It will resolve #29

### CODE REVIEW

**Comment by dalinaum** [comment]
Please review this @realm/java

**Comment by cmelchior** [comment]
👍

**Comment by kneth** [comment]
:+1:

**Comment by nhachicha** [comment]
👍

**Pull request merged**
